### ISSUE TITLE
Maps: Pop-ups, ...

### ISSUE THREAD

**Issue by ferranbarceloheras** [4s4/esm#16]
We are trying to introduce the pop-up to the countries in the map.

**Comment by 4s4** [comment]
<img  src="https://user-images.githubusercontent.com/56407142/70161221-ff87b280-16bb-11ea-8140-0153cf2ee2b1.jpeg" width="200" />

**Comment by 4s4** [comment]
examples here  https://uber.github.io/react-map-gl/#/Examples/geo

**Comment by 4s4** [comment]
TODO: add pop-pup with chart

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/bar-basic/
```
Highcharts.chart('container', {
            chart: {
                type: 'bar'
            },
            title: {
                text: 'yuhu'
            },
            xAxis: {
                categories: ['Apples', 'Bananas', 'Oranges']
            },
            yAxis: {
                title: {
                    text: 'Fruit eaten'
                }
            },

            series: [{
                name: 'Afga',
                data: [1, 0, 4]
            }]
        })
```

**Comment by 4s4** [comment]
<img width="668" alt="Screen Shot 2019-12-05 at 13 07 06" src="https://user-images.githubusercontent.com/56407142/70234160-5050e700-1760-11ea-9b2a-6b347675511b.png">
